### PR TITLE
Adding support to specify the network to be used

### PR DESCRIPTION
**Pull request by macoss**
Thank you @lschmierer for your work on this library. I'm new to Rust and I'm starting to work on some control code to use with my lighting network.  I ran into an issue with testing code on my Mac that has a wired and wireless connection.  The operating system was choosing the wireless interface. Thought this could be helpful for others. I would love any feedback on how this could be implemented better.

### CODE REVIEW

**Comment by lschmierer** [comment]
Thank you very much for your interest in this project. As you probably have seen, this library didn't received any updates for a pretty long time.
When I wrote this code, I was totally new to Rust, too. So I don't really know how good the quality of the library actually is.
In my opinion your code additions look fine, though. I think there is nothing that speaks against just merging it.

Once I had the vision of starting the implementation of the full ACN standard (maybe using the tokio async io stack, that evolved in the meantime since I worked on sACN), but since I don't have any actual projects needing this, I never done any work in this direction.

**Comment by lschmierer** [comment]
While I can merge this, I cannot publish a new version to crates.io at the moment. I won't have access to my computer for the next (at least one or two) weeks.
But you can off cause just use the git url in your Cargo.toml in the meantime.

**Comment by macoss** [comment]
Hey Lucas,

I found the crate and am very interested in it.  I’m a production director for a large church in the US.  We have 12 church campuses and I’m starting to work on some A/V control code software and really liked what I was reading about Rust.  I was a long time IT guy before switching over to the production world about 10 years ago and still enjoy coding. 

I have been doing some testing with your can crate on two different sACN to DMX converters and it seems to be working well.  I plan on starting small, by integrating the library with some GPIO code on a Raspberry PI for some wall controls at one of our buildings. As I go I might submit some more PRs if that is ok? 

Long term I’m planning on working on a more general control solution for the production industry that I would open source and from what I can see your work will be great for handling the ACN output.

**Comment by lschmierer** [comment]
Sounds great!

**Pull request merged**
